export class ListPaymentRequest {
    constructor(public LSID: string,
        public BRGNR: string,
        public AFTLNR: string,
        public VIEWUSER: string,
        public LDKD_BRUGER: string,
        public SPROG: string,
        public TIMEZONEID: string,
        public ACTION: string,
        public CBOSELFOLDER: string,
        public CBOSELPERIOD: string,
        public OPTPERIODTP: string,
        public CBOSELPAYSTAT: string,
        public TXIPERFROM: string,
        public TXIPERTO: string,
        public cboSelSortCrit: string,
        public CBOSELPAGESIZE: string,
        public BULKREFLBD: string,
        public ISBIGCUSTOMER: string,
        public txiAmountFrom: number,
        public txiAmountFromDec: number,
        public txiAmountTo: number,
        public txiAmountToDec: number,
        public cboCurrency: string,
        public cboCreateUsr: string,
        public cboApproveUsr: string,
        public cboDebAccount: string,
        public txiTextStr: string,
        public txiBeneNameStr: string,
        public txiBeneAccStr: string,
        public cboPaymType: string,
        public txiRfNr: string,
        public cboRfnrTp: string,
        public txiSenderID: string,
        public chkBulkDebit: string,
        public chkXtraFee: string) { }
}